version: '2'

services:

  mongodb:
    image: mongo:2.4
    container_name: "realworld-mongo"
    restart: always
    ports:
      - 27017:27017

  realwordback:
    image: cryptodraco/back_realworld:latest
    container_name: "realword-back"
    restart: always

    #environment:
    #  - INTERNAL_URL=http://woofapi:8080 #doit mapper hostname + port externe
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - 3000:3000

  realwordfront:
    image: cryptodraco/realwordfront:latest
    container_name: "realword-front"
    restart: always

    links:
      - realwordback
    ports:
      - 8080:8080
