version: '2'

services:

  mongodb:
    image: mongo:2.4
    container_name: "realworld-mongo"
    restart: always
    ports:
      - 27017:27018

  realwordback:
    image: cryptodraco/realword_back:0.0.1
    container_name: "realword-back"
    restart: always

    #environment:
    #  - INTERNAL_URL=http://woofapi:8080 #doit mapper hostname + port externe
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - 3000:3000

  realwordfront:
    image: cryptodraco/realword_front:0.0.1
    container_name: "realword-front"
    restart: always

    links:
      - realwordback
    ports:
      - 8080:5001
